Feature kafka consumer
CUBigDataClass/BigMood pull request #23
Opened 2019-04-22 18:11 UTC by SrishtiR

Added consumer service to obtain json object from kafka topic containing sentiment score.

2019-04-22 18:17 UTC, shreshtha-pankaj reviewed
I'll let you know how we can add things in the encrypted configuration today after or before class today.

2019-04-22 18:17 UTC, shreshtha-pankaj commented on service/KafkaConsumerService.js
> +    insertAllTrendsLocationWise(trends);
this will fail. Unless Redis cache service is updated.

2019-04-22 18:17 UTC, shreshtha-pankaj commented on service/KafkaConsumerService.js
> +import { insertAllTrendsLocationWise } from './RedisCacheService';
this will fail. Unless Redis cache service is updated.

2019-04-22 18:17 UTC, shreshtha-pankaj commented on service/KafkaConsumerService.js
> +let kafkaHost = '35.222.250.101:9092'
Lets put this in the config files we have.

2019-04-22 18:17 UTC, shreshtha-pankaj commented on service/KafkaConsumerService.js
> +const consumeTrendsFromKafka = () => {
could you add on error as well?

2019-04-22 18:17 UTC, shreshtha-pankaj commented on service/KafkaConsumerService.js
> +let options = {
put this in the configuration as well??

2019-04-22 18:19 UTC, AbigailFernandes requested changes

2019-04-22 18:19 UTC, AbigailFernandes commented on service/KafkaConsumerService.js
> +let kafkaHost = '35.222.250.101:9092'
Should be const kafkaHost. The IP should come from Config.

2019-04-22 18:19 UTC, AbigailFernandes commented on service/KafkaConsumerService.js
> +import { builtinModules } from 'module';
This import seems redundant. You don't seem to be using it anywhere

2019-04-22 18:19 UTC, AbigailFernandes commented on service/KafkaConsumerService.js
> +let options = {
You can remove this and always set it in the consumer object. This seems redundant too

2019-04-22 18:19 UTC, AbigailFernandes commented on service/KafkaConsumerService.js
> +  [
This should instead be 
```
  [
    {
      autoCommit: false
    },
  {
      fromOffset: 'latest'
    }
  ]
```

2019-04-22 23:29 UTC, juanhotencoding requested changes
have the changes been made?

2019-04-23 02:50 UTC, shreshtha-pankaj approved these changes

2019-04-23 02:52 UTC, merged